### PR TITLE
Stick to working version of tkinter-standalone

### PR DESCRIPTION
**Pull request by dwrobel**
Fixes the following flatpak build error:
 clinic/_tkinter.c.h:544:20: error: initializer element is not constant
 544 |     {"dooneevent", _PyCFunction_CAST(_tkinter_tkapp_dooneevent), \
 METH_FASTCALL, _tkinter_tkapp_dooneevent__doc__},

by sticking to the last working version.

The very latest revision is an adjustment for python 3.11 and does not compile with python 3.10.

### CODE REVIEW

**Comment by Harvie** [comment]
thanks
